config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pontos

  root 'pontos#index'

  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
end

app/models/ponto.rb
class Ponto < ActiveRecord::Base
  belongs_to :state
  geocoded_by :address
  after_validation :geocode

  auto_strip_attributes :logradouro, :squish => true
  auto_strip_attributes :cidade, :squish => true
  auto_strip_attributes :cep, :squish => true


  validates_presence_of :logradouro, :message => " - deve ser preenchido"
  validates_presence_of :cidade, :message => " - deve ser preenchido"
  validates_presence_of :state_id, :message => " - deve ser preenchido"

  def address
    state_acronym ||= state.acronym unless state.nil?
    [logradouro, cidade, state_acronym].reject(&:blank?).compact.join(', ')
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  has_many :pontos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/pontos_controller.rb
class PontosController < ApplicationController
  before_action :set_ponto, only: [:show, :edit, :update, :destroy]

  # GET /pontos
  # GET /pontos.json
  def index
     if (params[:state_id] && State.all.collect(&:id).include?(params[:state_id].to_i))
       @pontos = Ponto.where(state_id: params[:state_id])
     else
       @pontos = Ponto.all
     end

     @hash = Gmaps4rails.build_markers(@pontos) do |ponto, marker|
        marker.lat ponto.latitude
        marker.lng ponto.longitude
        marker.infowindow ponto.address
        marker.picture({
          "url" => "icon_32.png",
          "width" => 32,
          "height" => 32})
    end
  end

  # GET /pontos/1
  # GET /pontos/1.json
  def show

  end

  # GET /pontos/new
  def new
    @ponto = Ponto.new
  end

  # GET /pontos/1/edit
  def edit
  end

  # POST /pontos
  # POST /pontos.json
  def create
    @ponto = Ponto.new(ponto_params)
    #binding.pry

    respond_to do |format|
      if @ponto.save
        format.html { redirect_to @ponto, notice: 'Ponto was successfully created.' }
        format.json { render :show, status: :created, location: @ponto }
      else
        format.html { render :new }
        format.json { render json: @ponto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pontos/1
  # PATCH/PUT /pontos/1.json
  def update
    respond_to do |format|
      if @ponto.update(ponto_params)
        format.html { redirect_to @ponto, notice: 'Ponto was successfully updated.' }
        format.json { render :show, status: :ok, location: @ponto }
      else
        format.html { render :edit }
        format.json { render json: @ponto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pontos/1
  # DELETE /pontos/1.json
  def destroy
    @ponto.destroy
    respond_to do |format|
      format.html { redirect_to pontos_url, notice: 'Ponto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ponto
      @ponto = Ponto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ponto_params
      params.require(:ponto).permit(:logradouro, :cidade, :state_id, :cep)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pontos_helper.rb
module PontosHelper
  def state_options
    options_for_select(State.all.map {|s| [s.name, s.id] }, params[:state_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Amor no Cabide</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>


        <%= link_to(image_tag("/logo.png", :alt => "logo", :title => "Home", :class=>"images", :id=>"logo"), "/", :class => "navbar-brand") %>


      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav menu">
          <li><a href="#" data-toggle="modal" data-target="#modalAbout">Sobre nós</a></li>
          <li><a href="#" data-toggle="modal" data-target="#modalContact">Contato</a></li>
        </ul>

        

        <ul class="nav navbar-nav navbar-right">
          <%= link_to new_ponto_path, :class => 'btn btn-primary btn-lg' do %>
          <span class="glyphicon glyphicon-map-marker"></span>
          Cadastrar ponto
          <% end %>
        </ul>
      </div>

    </div>
  </div>
  <div class="">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= msg %>
    <% end %>
    <% end %>

    <%= yield %>

    <div class="container">

    </div>
    <!-- Modals -->
    <div class="modal fade" id="modalAbout" tabindex="-1" role="dialog" aria-labelledby="modalLabelAbout" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="modalLabelAbout">Sobre nós</h4>
          </div>
          <div class="modal-body">
            <p>O Amor no Cabide é um movimento para adesão da população: doe amor através de agasalhos em bom estado e quentinhos.<br/><br/>
              <b>Qual é o objetivo?</b><br/>
              Espalhar cabides pela cidade e promover a doação de agasalhos para quem precisa.<br/><br/>
              <b>Como funciona?</b><br/>
              - Todos podem participar do movimento;<br/>
              - Cada pessoa pode colocar roupas em cabides já existentes ou adicionar um novo pela cidade;<br/>
              - O movimento conta com o bom senso de todos para que os mais necessitados se apropriem das doações.<br/><br/>
              <b>Participe! ♥</b></p>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="modalContact" tabindex="-1" role="dialog" aria-labelledby="modalLabelContact" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="modalLabelContact">Contato</h4>
            </div>
            <div class="modal-body">
              Fale conosco...
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
  </html>

app/views/pages/about.html.erb
<div>
  O que é?

É um movimento para adesão da população: doe amor através de agasalhos em bom estado e quentinhos.

Qual é o objetivo?

Espalhar cabides pela cidade e promover a doação de agasalhos para quem precisa.

Como funciona?

- Todos podem participar do movimento;
- Cada pessoa pode colocar roupas em cabides já existentes ou adicionar um novo pela cidade;
- O movimento conta com o bom senso de todos para que os mais necessitados se apropriem das doações.

♥

</div>

app/views/pontos/_form.html.erb
<%= form_for(@ponto, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @ponto.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>Ops! Parece que você esqueceu de algo:</h4>

      <ul>
      <% @ponto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" style="display:none;">
    <%= f.label :latitude, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :latitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group" style="display:none;">
    <%= f.label :longitude, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :logradouro, :class => "col-sm-2 control-label required" %>
    <div class="col-sm-10">
      <%= f.text_field :logradouro, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cidade, :class => "col-sm-2 control-label required" %>
    <div class="col-sm-10">
      <%= f.text_field :cidade, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :estado, :class => "col-sm-2 control-label required" %>
    <div class="col-sm-10">
      <%= f.collection_select :state_id, State.all, :id, :name, {prompt: "Selecione um estado"}, {class: "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cep, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cep, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :value => "Salvar", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/pontos/_map_container.html.erb
<div class="map-container">
  <div id="map" class="map-canvas"></div>
</div>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/pontos/_right_table.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
        <th>Pontos Existentes</th>
    </tr>
  </thead>
  <tbody>
    <%= content_tag_for(:tr, @pontos) do |ponto| %>
      <td><%= ponto.address%></td>
    <% end %>
  </tbody>
</table>

app/views/pontos/edit.html.erb
<div class="page-header">
  <%= link_to pontos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @ponto, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing ponto</h1>
</div>

<%= render 'form' %>

app/views/pontos/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="page-container">
  <%= render partial: 'map_container' %>

  <div class="right-bar hidden-xs">
    <form class="navbar-form">
      <div class="form-group">
        <div class="col-sm-2">
          <%= select_tag("state_id", state_options, :prompt => "Selecione estado", :class => "form-control") %>
        </div>
      </div>
      <button type="submit" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-search"></span> Filtrar
      </button>
    </form>
    <%= render partial: 'right_table' %>
  </div>
</div>

app/views/pontos/new.html.erb
<div class="page-header">
  <!--<%= link_to pontos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <div class="title">-->
    <h2>Cadastrar Novo Cabide</h2>
  </div>

<%= render 'form' %>

app/views/pontos/show.html.erb
<div class="page-header">
  <%= link_to pontos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_ponto_path(@ponto), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h3>Onde está este cabide:</h3>
</div>

<dl class="dl-horizontal">
  <dt>Latitude:</dt>
  <dd><%= @ponto.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @ponto.longitude %></dd>

  <dt>Logradouro:</dt>
  <dd><%= @ponto.logradouro %></dd>

  <dt>Cidade:</dt>
  <dd><%= @ponto.cidade %></dd>

  <dt>Estado:</dt>
  <dd><%= @ponto.state.acronym %></dd>

  <dt>Cep:</dt>
  <dd><%= @ponto.cep %></dd>

</dl>